apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adservice.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.adservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adservice.name }}
    spec:
      containers:
        - name: {{ .Values.adservice.containerName }}
          image: {{ .Values.adservice.image }}
          ports:
            - containerPort: {{ .Values.adservice.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.adservice.env.PORT }}"
          resources:
            requests:
              cpu: {{ .Values.adservice.resources.requests.cpu }}
              memory: {{ .Values.adservice.resources.requests.memory }}
            limits:
              cpu: {{ .Values.adservice.resources.limits.cpu }}
              memory: {{ .Values.adservice.resources.limits.memory }}
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.adservice.containerPort }}"]
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.adservice.containerPort }}"]
