apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adservice.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.adservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.adservice.servicePort }}
      targetPort: {{ .Values.adservice.containerPort }}
