apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.emailservice.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.emailservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.emailservice.servicePort }}
      targetPort: {{ .Values.emailservice.containerPort }}
