apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.emailservice.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.emailservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.emailservice.name }}
    spec:
      containers:
        - name: {{ .Values.emailservice.containerName }}
          image: {{ .Values.emailservice.image }}
          ports:
            - containerPort: {{ .Values.emailservice.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.emailservice.env.PORT }}"
            - name: DISABLE_TRACING
              value: "{{ .Values.emailservice.env.DISABLE_TRACING }}"
            - name: DISABLE_PROFILER
              value: "{{ .Values.emailservice.env.DISABLE_PROFILER }}"
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.emailservice.containerPort }}"]
          livenessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.emailservice.containerPort }}"]
          resources:
            requests:
              cpu: {{ .Values.emailservice.resources.requests.cpu }}
              memory: {{ .Values.emailservice.resources.requests.memory }}
            limits:
              cpu: {{ .Values.emailservice.resources.limits.cpu }}
              memory: {{ .Values.emailservice.resources.limits.memory }}
