apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.containerName }}
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.frontend.env.PORT }}"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "{{ .Values.frontend.env.PRODUCT_CATALOG_SERVICE_ADDR }}"
            - name: CURRENCY_SERVICE_ADDR
              value: "{{ .Values.frontend.env.CURRENCY_SERVICE_ADDR }}"
            - name: CART_SERVICE_ADDR
              value: "{{ .Values.frontend.env.CART_SERVICE_ADDR }}"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "{{ .Values.frontend.env.RECOMMENDATION_SERVICE_ADDR }}"
            - name: SHIPPING_SERVICE_ADDR
              value: "{{ .Values.frontend.env.SHIPPING_SERVICE_ADDR }}"
            - name: CHECKOUT_SERVICE_ADDR
              value: "{{ .Values.frontend.env.CHECKOUT_SERVICE_ADDR }}"
            - name: AD_SERVICE_ADDR
              value: "{{ .Values.frontend.env.AD_SERVICE_ADDR }}"
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: {{ .Values.frontend.containerPort }}
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: {{ .Values.frontend.containerPort }}
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-liveness-probe"
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
