apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.paymentservice.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.paymentservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.paymentservice.servicePort }}
      targetPort: {{ .Values.paymentservice.containerPort }}
