apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.productcatalogservice.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.productcatalogservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.productcatalogservice.servicePort }}
      targetPort: {{ .Values.productcatalogservice.containerPort }}
