apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.productcatalogservice.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.productcatalogservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.productcatalogservice.name }}
    spec:
      containers:
        - name: {{ .Values.productcatalogservice.containerName }}
          image: {{ .Values.productcatalogservice.image }}
          ports:
            - containerPort: {{ .Values.productcatalogservice.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.productcatalogservice.env.PORT }}"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.productcatalogservice.containerPort }}"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.productcatalogservice.containerPort }}"]
          resources:
            requests:
              cpu: {{ .Values.productcatalogservice.resources.requests.cpu }}
              memory: {{ .Values.productcatalogservice.resources.requests.memory }}
            limits:
              cpu: {{ .Values.productcatalogservice.resources.limits.cpu }}
              memory: {{ .Values.productcatalogservice.resources.limits.memory }}
