apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.recommendationservice.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.recommendationservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.recommendationservice.name }}
    spec:
      containers:
        - name: {{ .Values.recommendationservice.containerName }}
          image: {{ .Values.recommendationservice.image }}
          ports:
            - containerPort: {{ .Values.recommendationservice.containerPort }}
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.recommendationservice.containerPort }}"]
          livenessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.recommendationservice.containerPort }}"]
          env:
            - name: PORT
              value: "{{ .Values.recommendationservice.env.PORT }}"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "{{ .Values.recommendationservice.env.PRODUCT_CATALOG_SERVICE_ADDR }}"
            - name: DISABLE_TRACING
              value: "{{ .Values.recommendationservice.env.DISABLE_TRACING }}"
            - name: DISABLE_PROFILER
              value: "{{ .Values.recommendationservice.env.DISABLE_PROFILER }}"
            - name: DISABLE_DEBUGGER
              value: "{{ .Values.recommendationservice.env.DISABLE_DEBUGGER }}"
          resources:
            requests:
              cpu: {{ .Values.recommendationservice.resources.requests.cpu }}
              memory: {{ .Values.recommendationservice.resources.requests.memory }}
            limits:
              cpu: {{ .Values.recommendationservice.resources.limits.cpu }}
              memory: {{ .Values.recommendationservice.resources.limits.memory }}
