emailservice:
  name: emailservice
  containerName: server
  image: akiltipu/emailservice:latest
  containerPort: 8080
  servicePort: 5000

  env:
    PORT: "8080"
    DISABLE_TRACING: "1"
    DISABLE_PROFILER: "1"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi


recommendationservice:
  name: recommendationservice
  containerName: server
  image: akiltipu/recommendationservice:latest
  containerPort: 8080
  servicePort: 8080

  env:
    PORT: "8080"
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    DISABLE_TRACING: "1"
    DISABLE_PROFILER: "1"
    DISABLE_DEBUGGER: "1"

  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi

paymentservice:
  name: paymentservice
  containerName: server
  image: akiltipu/paymentservice:latest
  containerPort: 50051
  servicePort: 50051

  env:
    PORT: "50051"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

productcatalogservice:
  name: productcatalogservice
  containerName: server
  image: akiltipu/productcatalogservice:latest
  containerPort: 3550
  servicePort: 3550

  env:
    PORT: "3550"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

currencyservice:
  name: currencyservice
  containerName: server
  image: akiltipu/currencyservice:latest
  containerPort: 7000
  servicePort: 7000

  env:
    PORT: "7000"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

shippingservice:
  name: shippingservice
  containerName: server
  image: akiltipu/shippingservice:latest
  containerPort: 50051
  servicePort: 50051

  env:
    PORT: "50051"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

adservice:
  name: adservice
  containerName: server
  image: akiltipu/adservice:latest
  containerPort: 9555
  servicePort: 9555

  env:
    PORT: "9555"

  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi

cartservice:
  name: cartservice
  containerName: server
  image: akiltipu/cartservice:latest
  containerPort: 7070
  servicePort: 7070

  env:
    REDIS_ADDR: "redis-cart:6379"

  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi

checkoutservice:
  name: checkoutservice
  containerName: server
  image: akiltipu/checkoutservice:latest
  containerPort: 5050
  servicePort: 5050

  env:
    PORT: "5050"
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    SHIPPING_SERVICE_ADDR: "shippingservice:50051"
    PAYMENT_SERVICE_ADDR: "paymentservice:50051"
    EMAIL_SERVICE_ADDR: "emailservice:5000"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    CART_SERVICE_ADDR: "cartservice:7070"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

frontend:
  name: frontend
  externalServiceName: frontend-external
  containerName: server
  image: akiltipu/frontend:latest
  containerPort: 8080
  servicePort: 80

  env:
    PORT: "8080"
    PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
    CURRENCY_SERVICE_ADDR: "currencyservice:7000"
    CART_SERVICE_ADDR: "cartservice:7070"
    RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
    SHIPPING_SERVICE_ADDR: "shippingservice:50051"
    CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
    AD_SERVICE_ADDR: "adservice:9555"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

rediscart:
  name: redis-cart
  containerName: redis
  image: redis:alpine
  containerPort: 6379
  servicePort: 6379

  volume:
    name: redis-data
    mountPath: /data

  resources:
    requests:
      cpu: 70m
      memory: 200Mi
    limits:
      cpu: 125m
      memory: 256Mi
